org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17.17
fabric_api_version=0.161.0+26.3
kotlin_version=2.4.20
fabric_language_kotlin_version=1.14.1+kotlin.2.4.20
kotlinx_serialization_json_version=1.11.0

server_version=0.1.0-alpha.3
maven_group=dev.boxloom
fabric_archives_base_name=boxloom
core_archives_base_name=boxloom-server-core
