plugins {
    id "org.jetbrains.kotlin.jvm"
    id "org.jetbrains.kotlin.plugin.serialization"
}

base {
    archivesName = project.core_archives_base_name
}

dependencies {
    implementation "io.ktor:ktor-server-auth:${project.ktor_version}"
    implementation "io.ktor:ktor-server-body-limit:${project.ktor_version}"
    implementation "io.ktor:ktor-server-cio:${project.ktor_version}"
    implementation "io.ktor:ktor-server-content-negotiation:${project.ktor_version}"
    implementation "io.ktor:ktor-server-sse:${project.ktor_version}"
    implementation "io.ktor:ktor-server-status-pages:${project.ktor_version}"
    implementation "io.ktor:ktor-serialization-kotlinx-json:${project.ktor_version}"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:${project.kotlinx_serialization_json_version}"
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit:${project.kotlin_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = "UTF-8"
}

kotlin {
    jvmToolchain(25)
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile).configureEach {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21)
    }
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
